export const exactUtilities: Record<string, Record<string, string>> = {
  display: {
    block: 'block',
    'inline-block': 'inline-block',
    inline: 'inline',
    flex: 'flex',
    'inline-flex': 'inline-flex',
    grid: 'grid',
    'inline-grid': 'inline-grid',
    contents: 'contents',
    'flow-root': 'flow-root',
    'inline-table': 'inline-table',
    'list-item': 'list-item',
    table: 'table',
    'table-caption': 'table-caption',
    'table-cell': 'table-cell',
    'table-column': 'table-column',
    'table-column-group': 'table-column-group',
    'table-footer-group': 'table-footer-group',
    'table-header-group': 'table-header-group',
    'table-row': 'table-row',
    'table-row-group': 'table-row-group',
    none: 'hidden'
  },
  position: {
    static: 'static',
    fixed: 'fixed',
    absolute: 'absolute',
    relative: 'relative',
    sticky: 'sticky'
  },
  visibility: { visible: 'visible', hidden: 'invisible', collapse: 'collapse' },
  fill: {
    none: 'fill-none',
    currentcolor: 'fill-current',
    currentColor: 'fill-current',
    inherit: 'fill-inherit',
    transparent: 'fill-transparent'
  },
  stroke: {
    none: 'stroke-none',
    currentcolor: 'stroke-current',
    currentColor: 'stroke-current',
    inherit: 'stroke-inherit',
    transparent: 'stroke-transparent'
  },
  'justify-content': {
    normal: 'justify-normal',
    'flex-start': 'justify-start',
    center: 'justify-center',
    'flex-end': 'justify-end',
    'space-between': 'justify-between',
    'space-around': 'justify-around',
    'space-evenly': 'justify-evenly',
    stretch: 'justify-stretch'
  },
  'align-items': {
    'flex-start': 'items-start',
    center: 'items-center',
    'flex-end': 'items-end',
    stretch: 'items-stretch',
    baseline: 'items-baseline',
    'last baseline': 'items-baseline-last'
  },
  'flex-direction': {
    row: 'flex-row',
    'row-reverse': 'flex-row-reverse',
    column: 'flex-col',
    'column-reverse': 'flex-col-reverse'
  },
  'flex-wrap': { wrap: 'flex-wrap', 'wrap-reverse': 'flex-wrap-reverse', nowrap: 'flex-nowrap' },
  flex: {
    none: 'flex-none',
    auto: 'flex-auto',
    initial: 'flex-initial',
    '1 1 0%': 'flex-1'
  },
  'align-content': {
    normal: 'content-normal',
    center: 'content-center',
    'flex-start': 'content-start',
    'flex-end': 'content-end',
    'space-between': 'content-between',
    'space-around': 'content-around',
    'space-evenly': 'content-evenly',
    stretch: 'content-stretch',
    baseline: 'content-baseline'
  },
  'align-self': {
    auto: 'self-auto',
    'flex-start': 'self-start',
    'flex-end': 'self-end',
    center: 'self-center',
    stretch: 'self-stretch',
    baseline: 'self-baseline',
    'last baseline': 'self-baseline-last'
  },
  'place-items': {
    start: 'place-items-start',
    end: 'place-items-end',
    center: 'place-items-center',
    baseline: 'place-items-baseline',
    stretch: 'place-items-stretch'
  },
  'place-content': {
    center: 'place-content-center',
    start: 'place-content-start',
    end: 'place-content-end',
    'space-between': 'place-content-between',
    'space-around': 'place-content-around',
    'space-evenly': 'place-content-evenly',
    stretch: 'place-content-stretch',
    baseline: 'place-content-baseline'
  },
  'place-self': {
    auto: 'place-self-auto',
    start: 'place-self-start',
    end: 'place-self-end',
    center: 'place-self-center',
    stretch: 'place-self-stretch'
  },
  'justify-items': {
    start: 'justify-items-start',
    end: 'justify-items-end',
    center: 'justify-items-center',
    stretch: 'justify-items-stretch'
  },
  'justify-self': {
    auto: 'justify-self-auto',
    start: 'justify-self-start',
    end: 'justify-self-end',
    center: 'justify-self-center',
    stretch: 'justify-self-stretch'
  },
  'grid-auto-flow': {
    row: 'grid-flow-row',
    column: 'grid-flow-col',
    dense: 'grid-flow-dense',
    'row dense': 'grid-flow-row-dense',
    'column dense': 'grid-flow-col-dense'
  },
  'grid-template-columns': { none: 'grid-cols-none', subgrid: 'grid-cols-subgrid' },
  'grid-template-rows': { none: 'grid-rows-none', subgrid: 'grid-rows-subgrid' },
  'grid-auto-columns': {
    auto: 'auto-cols-auto',
    min: 'auto-cols-min',
    max: 'auto-cols-max',
    fr: 'auto-cols-fr'
  },
  'grid-auto-rows': {
    auto: 'auto-rows-auto',
    min: 'auto-rows-min',
    max: 'auto-rows-max',
    fr: 'auto-rows-fr'
  },
  'text-align': {
    left: 'text-left',
    center: 'text-center',
    right: 'text-right',
    justify: 'text-justify',
    start: 'text-start',
    end: 'text-end'
  },
  'text-transform': {
    uppercase: 'uppercase',
    lowercase: 'lowercase',
    capitalize: 'capitalize',
    none: 'normal-case'
  },
  'font-style': { italic: 'italic', normal: 'not-italic' },
  'font-family': {
    sans: 'font-sans',
    serif: 'font-serif',
    monospace: 'font-mono',
    'ui-sans-serif, system-ui, sans-serif': 'font-sans',
    'ui-serif, georgia, cambria, "times new roman", times, serif': 'font-serif',
    'ui-monospace, sfmono-regular, menlo, monaco, consolas, "liberation mono", "courier new", monospace':
      'font-mono'
  },
  'font-variant-numeric': {
    normal: 'normal-nums',
    ordinal: 'ordinal',
    'slashed-zero': 'slashed-zero',
    'lining-nums': 'lining-nums',
    'oldstyle-nums': 'oldstyle-nums',
    'proportional-nums': 'proportional-nums',
    'tabular-nums': 'tabular-nums',
    'diagonal-fractions': 'diagonal-fractions',
    'stacked-fractions': 'stacked-fractions'
  },
  '-webkit-font-smoothing': { antialiased: 'antialiased', auto: 'subpixel-antialiased' },
  '-moz-osx-font-smoothing': { grayscale: 'antialiased', auto: 'subpixel-antialiased' },
  'font-stretch': {
    'ultra-condensed': 'font-stretch-ultra-condensed',
    'extra-condensed': 'font-stretch-extra-condensed',
    condensed: 'font-stretch-condensed',
    'semi-condensed': 'font-stretch-semi-condensed',
    normal: 'font-stretch-normal',
    'semi-expanded': 'font-stretch-semi-expanded',
    expanded: 'font-stretch-expanded',
    'extra-expanded': 'font-stretch-extra-expanded',
    'ultra-expanded': 'font-stretch-ultra-expanded'
  },
  'text-decoration-line': {
    underline: 'underline',
    overline: 'overline',
    'line-through': 'line-through',
    none: 'no-underline'
  },
  'border-style': {
    solid: 'border-solid',
    dashed: 'border-dashed',
    dotted: 'border-dotted',
    double: 'border-double',
    hidden: 'border-hidden',
    none: 'border-none'
  },
  'border-top-style': {
    solid: 'border-t-solid',
    dashed: 'border-t-dashed',
    dotted: 'border-t-dotted',
    double: 'border-t-double',
    hidden: 'border-t-hidden',
    none: 'border-t-none'
  },
  'border-right-style': {
    solid: 'border-r-solid',
    dashed: 'border-r-dashed',
    dotted: 'border-r-dotted',
    double: 'border-r-double',
    hidden: 'border-r-hidden',
    none: 'border-r-none'
  },
  'border-bottom-style': {
    solid: 'border-b-solid',
    dashed: 'border-b-dashed',
    dotted: 'border-b-dotted',
    double: 'border-b-double',
    hidden: 'border-b-hidden',
    none: 'border-b-none'
  },
  'border-left-style': {
    solid: 'border-l-solid',
    dashed: 'border-l-dashed',
    dotted: 'border-l-dotted',
    double: 'border-l-double',
    hidden: 'border-l-hidden',
    none: 'border-l-none'
  },
  'border-inline-start-style': {
    solid: 'border-s-solid',
    dashed: 'border-s-dashed',
    dotted: 'border-s-dotted',
    double: 'border-s-double',
    hidden: 'border-s-hidden',
    none: 'border-s-none'
  },
  'border-inline-end-style': {
    solid: 'border-e-solid',
    dashed: 'border-e-dashed',
    dotted: 'border-e-dotted',
    double: 'border-e-double',
    hidden: 'border-e-hidden',
    none: 'border-e-none'
  },
  'border-inline-style': {
    solid: 'border-x-solid',
    dashed: 'border-x-dashed',
    dotted: 'border-x-dotted',
    double: 'border-x-double',
    hidden: 'border-x-hidden',
    none: 'border-x-none'
  },
  'border-block-style': {
    solid: 'border-y-solid',
    dashed: 'border-y-dashed',
    dotted: 'border-y-dotted',
    double: 'border-y-double',
    hidden: 'border-y-hidden',
    none: 'border-y-none'
  },
  'outline-style': {
    solid: 'outline-solid',
    dashed: 'outline-dashed',
    dotted: 'outline-dotted',
    double: 'outline-double',
    none: 'outline-none'
  },
  'object-fit': {
    contain: 'object-contain',
    cover: 'object-cover',
    fill: 'object-fill',
    none: 'object-none',
    'scale-down': 'object-scale-down'
  },
  'object-position': {
    bottom: 'object-bottom',
    center: 'object-center',
    'center center': 'object-center',
    left: 'object-left',
    'left center': 'object-left',
    'left bottom': 'object-left-bottom',
    'left top': 'object-left-top',
    right: 'object-right',
    'right center': 'object-right',
    'right bottom': 'object-right-bottom',
    'right top': 'object-right-top',
    top: 'object-top',
    'center top': 'object-top',
    'center bottom': 'object-bottom'
  },
  'background-repeat': {
    repeat: 'bg-repeat',
    'no-repeat': 'bg-no-repeat',
    'repeat-x': 'bg-repeat-x',
    'repeat-y': 'bg-repeat-y',
    round: 'bg-repeat-round',
    space: 'bg-repeat-space'
  },
  'background-attachment': { fixed: 'bg-fixed', local: 'bg-local', scroll: 'bg-scroll' },
  'background-clip': {
    'border-box': 'bg-clip-border',
    'padding-box': 'bg-clip-padding',
    'content-box': 'bg-clip-content',
    text: 'bg-clip-text'
  },
  'background-origin': {
    'border-box': 'bg-origin-border',
    'padding-box': 'bg-origin-padding',
    'content-box': 'bg-origin-content'
  },
  'mask-image': { none: 'mask-none' },
  'mask-mode': { alpha: 'mask-alpha', luminance: 'mask-luminance' },
  'mask-size': { auto: 'mask-auto', contain: 'mask-contain', cover: 'mask-cover' },
  'mask-repeat': { repeat: 'mask-repeat', 'no-repeat': 'mask-no-repeat' },
  'mask-origin': {
    'border-box': 'mask-origin-border',
    'padding-box': 'mask-origin-padding',
    'content-box': 'mask-origin-content',
    'fill-box': 'mask-origin-fill',
    'stroke-box': 'mask-origin-stroke',
    'view-box': 'mask-origin-view'
  },
  'mask-clip': {
    'border-box': 'mask-clip-border',
    'padding-box': 'mask-clip-padding',
    'content-box': 'mask-clip-content',
    'fill-box': 'mask-clip-fill',
    'stroke-box': 'mask-clip-stroke',
    'view-box': 'mask-clip-view',
    'no-clip': 'mask-no-clip'
  },
  'clip-path': { none: 'not-sr-only' },
  'box-decoration-break': { slice: 'box-decoration-slice', clone: 'box-decoration-clone' },
  '-webkit-box-decoration-break': { slice: 'box-decoration-slice', clone: 'box-decoration-clone' },
  'background-size': { auto: 'bg-auto', cover: 'bg-cover', contain: 'bg-contain' },
  'background-position': {
    bottom: 'bg-bottom',
    center: 'bg-center',
    'center center': 'bg-center',
    left: 'bg-left',
    'left center': 'bg-left',
    'left bottom': 'bg-left-bottom',
    'left top': 'bg-left-top',
    right: 'bg-right',
    'right center': 'bg-right',
    'right bottom': 'bg-right-bottom',
    'right top': 'bg-right-top',
    top: 'bg-top',
    'center top': 'bg-top',
    'center bottom': 'bg-bottom'
  },
  'vertical-align': {
    baseline: 'align-baseline',
    top: 'align-top',
    middle: 'align-middle',
    bottom: 'align-bottom',
    'text-top': 'align-text-top',
    'text-bottom': 'align-text-bottom',
    sub: 'align-sub',
    super: 'align-super'
  },
  'white-space': {
    normal: 'whitespace-normal',
    nowrap: 'whitespace-nowrap',
    pre: 'whitespace-pre',
    'pre-line': 'whitespace-pre-line',
    'pre-wrap': 'whitespace-pre-wrap',
    'break-spaces': 'whitespace-break-spaces'
  },
  'word-break': { normal: 'break-normal', 'break-all': 'break-all', 'keep-all': 'break-keep' },
  'overflow-wrap': {
    'break-word': 'break-words',
    anywhere: 'wrap-anywhere',
    normal: 'wrap-normal'
  },
  'text-overflow': { ellipsis: 'text-ellipsis', clip: 'text-clip' },
  hyphens: { none: 'hyphens-none', manual: 'hyphens-manual', auto: 'hyphens-auto' },
  'list-style-position': { inside: 'list-inside', outside: 'list-outside' },
  'list-style-type': { disc: 'list-disc', decimal: 'list-decimal', none: 'list-none' },
  'table-layout': { auto: 'table-auto', fixed: 'table-fixed' },
  'caption-side': { top: 'caption-top', bottom: 'caption-bottom' },
  'border-collapse': { collapse: 'border-collapse', separate: 'border-separate' },
  'box-sizing': { 'border-box': 'box-border', 'content-box': 'box-content' },
  'aspect-ratio': { '1 / 1': 'aspect-square', '16 / 9': 'aspect-video', auto: 'aspect-auto' },
  'field-sizing': { fixed: 'field-sizing-fixed', content: 'field-sizing-content' },
  'text-wrap': {
    wrap: 'text-wrap',
    nowrap: 'text-nowrap',
    balance: 'text-balance',
    pretty: 'text-pretty'
  },
  isolation: { isolate: 'isolate', auto: 'isolation-auto' },
  float: { right: 'float-right', left: 'float-left', none: 'float-none' },
  clear: { left: 'clear-left', right: 'clear-right', both: 'clear-both', none: 'clear-none' },
  appearance: { none: 'appearance-none', auto: 'appearance-auto' },
  'color-scheme': {
    normal: 'scheme-normal',
    dark: 'scheme-dark',
    light: 'scheme-light',
    'light dark': 'scheme-light-dark',
    'only dark': 'scheme-only-dark',
    'only light': 'scheme-only-light'
  },
  'mix-blend-mode': {
    normal: 'mix-blend-normal',
    multiply: 'mix-blend-multiply',
    screen: 'mix-blend-screen',
    overlay: 'mix-blend-overlay',
    darken: 'mix-blend-darken',
    lighten: 'mix-blend-lighten',
    'color-dodge': 'mix-blend-color-dodge',
    'color-burn': 'mix-blend-color-burn',
    'hard-light': 'mix-blend-hard-light',
    'soft-light': 'mix-blend-soft-light',
    difference: 'mix-blend-difference',
    exclusion: 'mix-blend-exclusion',
    hue: 'mix-blend-hue',
    saturation: 'mix-blend-saturation',
    color: 'mix-blend-color',
    luminosity: 'mix-blend-luminosity',
    'plus-darker': 'mix-blend-plus-darker',
    'plus-lighter': 'mix-blend-plus-lighter'
  },
  'background-blend-mode': {
    normal: 'bg-blend-normal',
    multiply: 'bg-blend-multiply',
    screen: 'bg-blend-screen',
    overlay: 'bg-blend-overlay',
    darken: 'bg-blend-darken',
    lighten: 'bg-blend-lighten',
    'color-dodge': 'bg-blend-color-dodge',
    'color-burn': 'bg-blend-color-burn',
    'hard-light': 'bg-blend-hard-light',
    'soft-light': 'bg-blend-soft-light',
    difference: 'bg-blend-difference',
    exclusion: 'bg-blend-exclusion',
    hue: 'bg-blend-hue',
    saturation: 'bg-blend-saturation',
    color: 'bg-blend-color',
    luminosity: 'bg-blend-luminosity'
  },
  'overscroll-behavior': {
    auto: 'overscroll-auto',
    contain: 'overscroll-contain',
    none: 'overscroll-none'
  },
  'overscroll-behavior-x': {
    auto: 'overscroll-x-auto',
    contain: 'overscroll-x-contain',
    none: 'overscroll-x-none'
  },
  'overscroll-behavior-y': {
    auto: 'overscroll-y-auto',
    contain: 'overscroll-y-contain',
    none: 'overscroll-y-none'
  },
  'scrollbar-width': { auto: 'scrollbar-auto', thin: 'scrollbar-thin', none: 'scrollbar-none' },
  'scrollbar-gutter': {
    stable: 'scrollbar-gutter-stable',
    'stable both-edges': 'scrollbar-gutter-both-edges'
  },
  'mask-type': { alpha: 'mask-type-alpha', luminance: 'mask-type-luminance' },
  'mask-composite': {
    add: 'mask-composite-add',
    subtract: 'mask-composite-subtract',
    intersect: 'mask-composite-intersect',
    exclude: 'mask-composite-exclude'
  },
  'scroll-behavior': { auto: 'scroll-auto', smooth: 'scroll-smooth' },
  'touch-action': {
    auto: 'touch-auto',
    none: 'touch-none',
    'pan-x': 'touch-pan-x',
    'pan-left': 'touch-pan-left',
    'pan-right': 'touch-pan-right',
    'pan-y': 'touch-pan-y',
    'pan-up': 'touch-pan-up',
    'pan-down': 'touch-pan-down',
    manipulation: 'touch-manipulation'
  },
  'will-change': {
    auto: 'will-change-auto',
    scroll: 'will-change-scroll',
    contents: 'will-change-contents',
    transform: 'will-change-transform'
  },
  contain: {
    none: 'contain-none',
    content: 'contain-content',
    strict: 'contain-strict',
    size: 'contain-size',
    layout: 'contain-layout',
    paint: 'contain-paint',
    style: 'contain-style',
    'inline-size': 'contain-inline-size'
  },
  'break-before': {
    auto: 'break-before-auto',
    avoid: 'break-before-avoid',
    all: 'break-before-all',
    'avoid-page': 'break-before-avoid-page',
    page: 'break-before-page',
    left: 'break-before-left',
    right: 'break-before-right',
    column: 'break-before-column'
  },
  'break-after': {
    auto: 'break-after-auto',
    avoid: 'break-after-avoid',
    all: 'break-after-all',
    'avoid-page': 'break-after-avoid-page',
    page: 'break-after-page',
    left: 'break-after-left',
    right: 'break-after-right',
    column: 'break-after-column'
  },
  'break-inside': {
    auto: 'break-inside-auto',
    avoid: 'break-inside-avoid',
    'avoid-page': 'break-inside-avoid-page',
    'avoid-column': 'break-inside-avoid-column'
  },
  'forced-color-adjust': { auto: 'forced-color-adjust-auto', none: 'forced-color-adjust-none' },
  filter: { none: 'filter-none' },
  'backdrop-filter': { none: 'backdrop-filter-none' },
  'box-shadow': { none: 'shadow-none' },
  'text-shadow': { none: 'text-shadow-none' },
  'backface-visibility': { hidden: 'backface-hidden', visible: 'backface-visible' },
  perspective: {
    none: 'perspective-none',
    '100px': 'perspective-dramatic',
    '300px': 'perspective-near',
    '500px': 'perspective-normal',
    '800px': 'perspective-midrange',
    '1200px': 'perspective-distant'
  },
  'transform-style': { 'preserve-3d': 'transform-3d', flat: 'transform-flat' },
  'transform-origin': {
    center: 'origin-center',
    top: 'origin-top',
    'top right': 'origin-top-right',
    right: 'origin-right',
    'bottom right': 'origin-bottom-right',
    bottom: 'origin-bottom',
    'bottom left': 'origin-bottom-left',
    left: 'origin-left',
    'top left': 'origin-top-left',
    '50% 50%': 'origin-center',
    '100% 0': 'origin-top-right',
    '100% 0%': 'origin-top-right',
    '100% 100%': 'origin-bottom-right',
    '50% 100%': 'origin-bottom',
    '0 100%': 'origin-bottom-left',
    '0% 100%': 'origin-bottom-left',
    '0 50%': 'origin-left',
    '0% 50%': 'origin-left',
    '0 0': 'origin-top-left',
    '0% 0%': 'origin-top-left'
  },
  'perspective-origin': {
    center: 'perspective-origin-center',
    top: 'perspective-origin-top',
    'top right': 'perspective-origin-top-right',
    right: 'perspective-origin-right',
    'bottom right': 'perspective-origin-bottom-right',
    bottom: 'perspective-origin-bottom',
    'bottom left': 'perspective-origin-bottom-left',
    left: 'perspective-origin-left',
    'top left': 'perspective-origin-top-left',
    '100% 0': 'perspective-origin-top-right',
    '100% 0%': 'perspective-origin-top-right',
    '100% 100%': 'perspective-origin-bottom-right',
    '0 100%': 'perspective-origin-bottom-left',
    '0% 100%': 'perspective-origin-bottom-left',
    '0 0': 'perspective-origin-top-left',
    '0% 0%': 'perspective-origin-top-left'
  },
  'scroll-snap-align': {
    start: 'snap-start',
    end: 'snap-end',
    center: 'snap-center',
    none: 'snap-align-none'
  },
  'scroll-snap-type': { none: 'snap-none' },
  'scroll-snap-stop': { normal: 'snap-normal', always: 'snap-always' },
  'transition-timing-function': {
    linear: 'ease-linear',
    ease: 'ease-in-out',
    'ease-in': 'ease-in',
    'ease-out': 'ease-out',
    'ease-in-out': 'ease-in-out'
  },
  'transition-property': {
    all: 'transition-all',
    none: 'transition-none',
    color: 'transition-colors',
    opacity: 'transition-opacity',
    shadow: 'transition-shadow',
    transform: 'transition-transform'
  },
  'transition-behavior': { normal: 'transition-normal', 'allow-discrete': 'transition-discrete' },
  animation: { none: 'animate-none' },
  'animation-name': { none: 'animate-none' },
  'background-image': { none: 'bg-none' },
  content: { none: 'content-none' },
  'accent-color': { auto: 'accent-auto' },
  'caret-color': { auto: 'caret-auto' },
  'list-style-image': { none: 'list-image-none' },
  'text-decoration-style': {
    solid: 'decoration-solid',
    double: 'decoration-double',
    dotted: 'decoration-dotted',
    dashed: 'decoration-dashed',
    wavy: 'decoration-wavy'
  },
  'text-decoration-thickness': {
    auto: 'decoration-auto',
    'from-font': 'decoration-from-font',
    '0px': 'decoration-0',
    '1px': 'decoration-1',
    '2px': 'decoration-2',
    '4px': 'decoration-4',
    '8px': 'decoration-8'
  },
  'text-underline-offset': {
    auto: 'underline-offset-auto',
    '0px': 'underline-offset-0',
    '1px': 'underline-offset-1',
    '2px': 'underline-offset-2',
    '4px': 'underline-offset-4',
    '8px': 'underline-offset-8'
  },
  'font-weight': {
    '100': 'font-thin',
    '200': 'font-extralight',
    '300': 'font-light',
    '400': 'font-normal',
    '500': 'font-medium',
    '600': 'font-semibold',
    '700': 'font-bold',
    '800': 'font-extrabold',
    '900': 'font-black',
    bold: 'font-bold',
    normal: 'font-normal'
  }
}

export const arbitraryPrefixes: Record<string, string> = {
  width: 'w',
  height: 'h',
  'inline-size': 'w',
  'block-size': 'h',
  'flex-basis': 'basis',
  'min-width': 'min-w',
  'min-height': 'min-h',
  'min-inline-size': 'min-w',
  'min-block-size': 'min-h',
  'max-width': 'max-w',
  'max-height': 'max-h',
  'max-inline-size': 'max-w',
  'max-block-size': 'max-h',
  margin: 'm',
  'margin-top': 'mt',
  'margin-right': 'mr',
  'margin-bottom': 'mb',
  'margin-left': 'ml',
  'margin-inline-start': 'ms',
  'margin-inline-end': 'me',
  'margin-inline': 'mx',
  'margin-block': 'my',
  'margin-block-start': 'mt',
  'margin-block-end': 'mb',
  top: 'top',
  right: 'right',
  bottom: 'bottom',
  left: 'left',
  'inset-inline-start': 'start',
  'inset-inline-end': 'end',
  padding: 'p',
  'padding-top': 'pt',
  'padding-right': 'pr',
  'padding-bottom': 'pb',
  'padding-left': 'pl',
  'padding-inline-start': 'ps',
  'padding-inline-end': 'pe',
  'padding-inline': 'px',
  'padding-block': 'py',
  'padding-block-start': 'pt',
  'padding-block-end': 'pb',
  gap: 'gap',
  'row-gap': 'gap-y',
  'column-gap': 'gap-x',
  'text-indent': 'indent',
  'border-spacing': 'border-spacing',
  'border-spacing-x': 'border-spacing-x',
  'border-spacing-y': 'border-spacing-y',
  'scroll-margin': 'scroll-m',
  'scroll-margin-top': 'scroll-mt',
  'scroll-margin-right': 'scroll-mr',
  'scroll-margin-bottom': 'scroll-mb',
  'scroll-margin-left': 'scroll-ml',
  'scroll-margin-inline-start': 'scroll-ms',
  'scroll-margin-inline-end': 'scroll-me',
  'scroll-margin-inline': 'scroll-mx',
  'scroll-margin-block': 'scroll-my',
  'scroll-margin-block-start': 'scroll-mt',
  'scroll-margin-block-end': 'scroll-mb',
  'scroll-padding': 'scroll-p',
  'scroll-padding-top': 'scroll-pt',
  'scroll-padding-right': 'scroll-pr',
  'scroll-padding-bottom': 'scroll-pb',
  'scroll-padding-left': 'scroll-pl',
  'scroll-padding-inline-start': 'scroll-ps',
  'scroll-padding-inline-end': 'scroll-pe',
  'scroll-padding-inline': 'scroll-px',
  'scroll-padding-block': 'scroll-py',
  'scroll-padding-block-start': 'scroll-pt',
  'scroll-padding-block-end': 'scroll-pb',
  color: 'text',
  'background-color': 'bg',
  'background-image': 'bg',
  '-webkit-line-clamp': 'line-clamp',
  'line-clamp': 'line-clamp',
  fill: 'fill',
  stroke: 'stroke',
  'border-color': 'border',
  'border-top-color': 'border-t',
  'border-right-color': 'border-r',
  'border-bottom-color': 'border-b',
  'border-left-color': 'border-l',
  'border-inline-start-color': 'border-s',
  'border-inline-end-color': 'border-e',
  'border-inline-color': 'border-x',
  'border-block-color': 'border-y',
  'outline-color': 'outline',
  'text-decoration-color': 'decoration',
  'caret-color': 'caret',
  'accent-color': 'accent',
  'border-width': 'border',
  'border-top-width': 'border-t',
  'border-right-width': 'border-r',
  'border-bottom-width': 'border-b',
  'border-left-width': 'border-l',
  'border-inline-start-width': 'border-s',
  'border-inline-end-width': 'border-e',
  'border-inline-width': 'border-x',
  'border-block-width': 'border-y',
  'stroke-width': 'stroke',
  'border-radius': 'rounded',
  'border-top-left-radius': 'rounded-tl',
  'border-top-right-radius': 'rounded-tr',
  'border-bottom-right-radius': 'rounded-br',
  'border-bottom-left-radius': 'rounded-bl',
  'border-start-start-radius': 'rounded-ss',
  'border-start-end-radius': 'rounded-se',
  'border-end-end-radius': 'rounded-ee',
  'border-end-start-radius': 'rounded-es',
  opacity: 'opacity',
  'z-index': 'z',
  'font-size': 'text',
  'line-height': 'leading',
  'letter-spacing': 'tracking',
  'outline-width': 'outline',
  'outline-offset': 'outline-offset',
  'box-shadow': 'shadow',
  filter: 'filter',
  'backdrop-filter': 'backdrop-filter',
  rotate: 'rotate',
  scale: 'scale',
  translate: 'translate',
  'grid-template-columns': 'grid-cols',
  'grid-template-rows': 'grid-rows',
  'transition-property': 'transition',
  'transition-duration': 'duration',
  'transition-delay': 'delay',
  'transition-timing-function': 'ease',
  animation: 'animate',
  'animation-name': 'animate',
  'animation-duration': 'duration',
  'animation-delay': 'delay',
  'animation-timing-function': 'ease',
  'animation-iteration-count': 'animate-iteration',
  perspective: 'perspective',
  'mask-position': 'mask-position',
  'mask-image': 'mask',
  'text-shadow': 'text-shadow',
  'clip-path': 'clip-path',
  'grid-column': 'col',
  'grid-column-start': 'col-start',
  'grid-column-end': 'col-end',
  'grid-row': 'row',
  'grid-row-start': 'row-start',
  'grid-row-end': 'row-end',
  cursor: 'cursor',
  content: 'content',
  'list-style-type': 'list',
  'list-style-image': 'list-image',
  'will-change': 'will-change',
  contain: 'contain',
  'mask-size': 'mask-size',
  'mask-repeat': 'mask-repeat',
  'mask-clip': 'mask-clip',
  'mask-origin': 'mask-origin',
  'mask-mode': 'mask-mode',
  'mask-composite': 'mask-composite',
  'font-family': 'font',
  'font-weight': 'font',
  'font-stretch': 'font-stretch',
  'background-position-x': 'bg-position-x',
  'background-position-y': 'bg-position-y',
  'column-count': 'columns',
  'column-width': 'columns',
  'aspect-ratio': 'aspect',
  'object-position': 'object',
  order: 'order',
  'tab-size': 'tab',
  zoom: 'zoom',
  'flex-grow': 'grow',
  'flex-shrink': 'shrink',
  'word-spacing': 'word-spacing',
  hyphens: 'hyphens',
  'scrollbar-color': 'scrollbar-color',
  'font-feature-settings': 'font-feature',
  'perspective-origin': 'perspective-origin',
  'column-rule-color': 'column-rule',
  'column-rule-width': 'column-rule',
  'column-rule-style': 'column-rule',
  'stroke-dasharray': 'stroke-dasharray',
  'stroke-dashoffset': 'stroke-dashoffset',
  'stroke-linecap': 'stroke-linecap',
  'stroke-linejoin': 'stroke-linejoin',
  'image-rendering': 'image-render',
  'paint-order': 'paint-order',
  'shape-outside': 'shape-outside',
  'shape-margin': 'shape-margin',
  'shape-image-threshold': 'shape-image-threshold'
}

export const spacingProperties = new Set([
  'width',
  'height',
  'min-width',
  'min-height',
  'max-width',
  'max-height',
  'inline-size',
  'block-size',
  'min-inline-size',
  'min-block-size',
  'max-inline-size',
  'max-block-size',
  'flex-basis',
  'margin',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'margin-inline-start',
  'margin-inline-end',
  'margin-inline',
  'margin-block',
  'margin-block-start',
  'margin-block-end',
  'padding',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',
  'padding-inline-start',
  'padding-inline-end',
  'padding-inline',
  'padding-block',
  'padding-block-start',
  'padding-block-end',
  'top',
  'right',
  'bottom',
  'left',
  'inset-inline-start',
  'inset-inline-end',
  'gap',
  'row-gap',
  'column-gap',
  'text-indent',
  'border-spacing',
  'border-spacing-x',
  'border-spacing-y',
  'scroll-margin',
  'scroll-margin-top',
  'scroll-margin-right',
  'scroll-margin-bottom',
  'scroll-margin-left',
  'scroll-margin-inline-start',
  'scroll-margin-inline-end',
  'scroll-margin-inline',
  'scroll-margin-block',
  'scroll-margin-block-start',
  'scroll-margin-block-end',
  'scroll-padding',
  'scroll-padding-top',
  'scroll-padding-right',
  'scroll-padding-bottom',
  'scroll-padding-left',
  'scroll-padding-inline-start',
  'scroll-padding-inline-end',
  'scroll-padding-inline',
  'scroll-padding-block',
  'scroll-padding-block-start',
  'scroll-padding-block-end',
  'border-width',
  'border-top-width',
  'border-right-width',
  'border-bottom-width',
  'border-left-width',
  'border-inline-start-width',
  'border-inline-end-width',
  'border-inline-width',
  'border-block-width',
  'border-radius',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-bottom-right-radius',
  'border-bottom-left-radius',
  'border-start-start-radius',
  'border-start-end-radius',
  'border-end-end-radius',
  'border-end-start-radius',
  'font-size',
  'line-height',
  'letter-spacing',
  'outline-width',
  'outline-offset'
])

export const valueAliases: Record<string, Record<string, string>> = {
  width: {
    auto: 'w-auto',
    '50%': 'w-1/2',
    '33.333333%': 'w-1/3',
    '66.666667%': 'w-2/3',
    '25%': 'w-1/4',
    '75%': 'w-3/4',
    '100%': 'w-full',
    '100vw': 'w-screen',
    '100dvw': 'w-dvw',
    '100lvw': 'w-lvw',
    '100svw': 'w-svw',
    'min-content': 'w-min',
    'max-content': 'w-max',
    'fit-content': 'w-fit'
  },
  height: {
    auto: 'h-auto',
    '50%': 'h-1/2',
    '33.333333%': 'h-1/3',
    '66.666667%': 'h-2/3',
    '25%': 'h-1/4',
    '75%': 'h-3/4',
    '100%': 'h-full',
    '100vh': 'h-screen',
    '100dvh': 'h-dvh',
    '100lvh': 'h-lvh',
    '100svh': 'h-svh',
    'min-content': 'h-min',
    'max-content': 'h-max',
    'fit-content': 'h-fit'
  },
  'inline-size': {
    auto: 'w-auto',
    '100%': 'w-full',
    '100vw': 'w-screen',
    '100dvw': 'w-dvw',
    '100lvw': 'w-lvw',
    '100svw': 'w-svw',
    'min-content': 'w-min',
    'max-content': 'w-max',
    'fit-content': 'w-fit'
  },
  'block-size': {
    auto: 'h-auto',
    '100%': 'h-full',
    '100vh': 'h-screen',
    '100dvh': 'h-dvh',
    '100lvh': 'h-lvh',
    '100svh': 'h-svh',
    'min-content': 'h-min',
    'max-content': 'h-max',
    'fit-content': 'h-fit'
  },
  'flex-basis': {
    auto: 'basis-auto',
    '100%': 'basis-full',
    '50%': 'basis-1/2',
    '33.333333%': 'basis-1/3',
    '66.666667%': 'basis-2/3',
    '25%': 'basis-1/4',
    '75%': 'basis-3/4',
    '20%': 'basis-1/5',
    '40%': 'basis-2/5',
    '60%': 'basis-3/5',
    '80%': 'basis-4/5',
    '16.666667%': 'basis-1/6',
    '83.333333%': 'basis-5/6'
  },
  'min-width': {
    '50%': 'min-w-1/2',
    '100%': 'min-w-full',
    '100vw': 'min-w-screen',
    '100dvw': 'min-w-dvw',
    '100lvw': 'min-w-lvw',
    '100svw': 'min-w-svw',
    'min-content': 'min-w-min',
    'max-content': 'min-w-max',
    'fit-content': 'min-w-fit'
  },
  'min-height': {
    '50%': 'min-h-1/2',
    '100%': 'min-h-full',
    '100vh': 'min-h-screen',
    '100dvh': 'min-h-dvh',
    '100lvh': 'min-h-lvh',
    '100svh': 'min-h-svh',
    'min-content': 'min-h-min',
    'max-content': 'min-h-max',
    'fit-content': 'min-h-fit'
  },
  'max-width': {
    '50%': 'max-w-1/2',
    '100%': 'max-w-full',
    '100vw': 'max-w-screen',
    '100dvw': 'max-w-dvw',
    '100lvw': 'max-w-lvw',
    '100svw': 'max-w-svw',
    'min-content': 'max-w-min',
    'max-content': 'max-w-max',
    'fit-content': 'max-w-fit',
    none: 'max-w-none'
  },
  'max-height': {
    '50%': 'max-h-1/2',
    '100%': 'max-h-full',
    '100vh': 'max-h-screen',
    '100dvh': 'max-h-dvh',
    '100lvh': 'max-h-lvh',
    '100svh': 'max-h-svh',
    'min-content': 'max-h-min',
    'max-content': 'max-h-max',
    'fit-content': 'max-h-fit',
    none: 'max-h-none'
  },
  'min-inline-size': {
    '100%': 'min-w-full',
    '100vw': 'min-w-screen',
    'min-content': 'min-w-min',
    'max-content': 'min-w-max',
    'fit-content': 'min-w-fit'
  },
  'min-block-size': {
    '100%': 'min-h-full',
    '100vh': 'min-h-screen',
    'min-content': 'min-h-min',
    'max-content': 'min-h-max',
    'fit-content': 'min-h-fit'
  },
  'max-inline-size': {
    '100%': 'max-w-full',
    '100vw': 'max-w-screen',
    'min-content': 'max-w-min',
    'max-content': 'max-w-max',
    'fit-content': 'max-w-fit',
    none: 'max-w-none'
  },
  'max-block-size': {
    '100%': 'max-h-full',
    '100vh': 'max-h-screen',
    'min-content': 'max-h-min',
    'max-content': 'max-h-max',
    'fit-content': 'max-h-fit',
    none: 'max-h-none'
  },
  margin: { auto: 'm-auto' },
  'margin-top': { auto: 'mt-auto' },
  'margin-right': { auto: 'mr-auto' },
  'margin-bottom': { auto: 'mb-auto' },
  'margin-left': { auto: 'ml-auto' },
  'border-radius': {
    '0': 'rounded-none',
    '0px': 'rounded-none',
    '0.125rem': 'rounded-xs',
    '2px': 'rounded-xs',
    '0.25rem': 'rounded-sm',
    '4px': 'rounded-sm',
    '0.375rem': 'rounded-md',
    '6px': 'rounded-md',
    '0.5rem': 'rounded-lg',
    '8px': 'rounded-lg',
    '0.75rem': 'rounded-xl',
    '12px': 'rounded-xl',
    '1rem': 'rounded-2xl',
    '16px': 'rounded-2xl',
    '1.5rem': 'rounded-3xl',
    '24px': 'rounded-3xl',
    '9999px': 'rounded-full'
  },
  'border-top-left-radius': {
    '0': 'rounded-tl-none',
    '0px': 'rounded-tl-none',
    '0.25rem': 'rounded-tl-sm',
    '4px': 'rounded-tl-sm',
    '0.5rem': 'rounded-tl-lg',
    '8px': 'rounded-tl-lg',
    '9999px': 'rounded-tl-full'
  },
  'border-top-right-radius': {
    '0': 'rounded-tr-none',
    '0px': 'rounded-tr-none',
    '0.25rem': 'rounded-tr-sm',
    '4px': 'rounded-tr-sm',
    '0.5rem': 'rounded-tr-lg',
    '8px': 'rounded-tr-lg',
    '9999px': 'rounded-tr-full'
  },
  'border-bottom-right-radius': {
    '0': 'rounded-br-none',
    '0px': 'rounded-br-none',
    '0.25rem': 'rounded-br-sm',
    '4px': 'rounded-br-sm',
    '0.5rem': 'rounded-br-lg',
    '8px': 'rounded-br-lg',
    '9999px': 'rounded-br-full'
  },
  'border-bottom-left-radius': {
    '0': 'rounded-bl-none',
    '0px': 'rounded-bl-none',
    '0.25rem': 'rounded-bl-sm',
    '4px': 'rounded-bl-sm',
    '0.5rem': 'rounded-bl-lg',
    '8px': 'rounded-bl-lg',
    '9999px': 'rounded-bl-full'
  },
  'border-start-start-radius': {
    '0': 'rounded-ss-none',
    '0px': 'rounded-ss-none',
    '0.25rem': 'rounded-ss-sm',
    '4px': 'rounded-ss-sm',
    '0.5rem': 'rounded-ss-lg',
    '8px': 'rounded-ss-lg',
    '9999px': 'rounded-ss-full'
  },
  'border-start-end-radius': {
    '0': 'rounded-se-none',
    '0px': 'rounded-se-none',
    '0.25rem': 'rounded-se-sm',
    '4px': 'rounded-se-sm',
    '0.5rem': 'rounded-se-lg',
    '8px': 'rounded-se-lg',
    '9999px': 'rounded-se-full'
  },
  'border-end-end-radius': {
    '0': 'rounded-ee-none',
    '0px': 'rounded-ee-none',
    '0.25rem': 'rounded-ee-sm',
    '4px': 'rounded-ee-sm',
    '0.5rem': 'rounded-ee-lg',
    '8px': 'rounded-ee-lg',
    '9999px': 'rounded-ee-full'
  },
  'border-end-start-radius': {
    '0': 'rounded-es-none',
    '0px': 'rounded-es-none',
    '0.25rem': 'rounded-es-sm',
    '4px': 'rounded-es-sm',
    '0.5rem': 'rounded-es-lg',
    '8px': 'rounded-es-lg',
    '9999px': 'rounded-es-full'
  },
  columns: { auto: 'columns-auto' },
  'font-size': {
    '12px': 'text-xs',
    '0.75rem': 'text-xs',
    '14px': 'text-sm',
    '0.875rem': 'text-sm',
    '16px': 'text-base',
    '1rem': 'text-base',
    '18px': 'text-lg',
    '1.125rem': 'text-lg',
    '20px': 'text-xl',
    '1.25rem': 'text-xl',
    '24px': 'text-2xl',
    '1.5rem': 'text-2xl',
    '30px': 'text-3xl',
    '1.875rem': 'text-3xl',
    '36px': 'text-4xl',
    '2.25rem': 'text-4xl',
    '48px': 'text-5xl',
    '3rem': 'text-5xl',
    '60px': 'text-6xl',
    '3.75rem': 'text-6xl',
    '72px': 'text-7xl',
    '4.5rem': 'text-7xl',
    '96px': 'text-8xl',
    '6rem': 'text-8xl',
    '128px': 'text-9xl',
    '8rem': 'text-9xl'
  },
  'line-height': {
    '16px': 'leading-4',
    '1rem': 'leading-4',
    '20px': 'leading-5',
    '1.25rem': 'leading-5',
    '24px': 'leading-6',
    '1.5rem': 'leading-6',
    '28px': 'leading-7',
    '1.75rem': 'leading-7',
    '32px': 'leading-8',
    '2rem': 'leading-8',
    '1': 'leading-none',
    normal: 'leading-normal',
    '1.25': 'leading-tight',
    '1.375': 'leading-snug',
    '1.5': 'leading-normal',
    '1.625': 'leading-relaxed',
    '2': 'leading-loose'
  },
  'letter-spacing': {
    normal: 'tracking-normal',
    '-0.05em': 'tracking-tighter',
    '-0.025em': 'tracking-tight',
    '0.025em': 'tracking-wide',
    '0.05em': 'tracking-wider',
    '0.1em': 'tracking-widest'
  },
  'outline-width': {
    '0': 'outline-0',
    '0px': 'outline-0',
    '1px': 'outline-1',
    '2px': 'outline-2',
    '4px': 'outline-4',
    '8px': 'outline-8'
  },
  'outline-offset': {
    '0': 'outline-offset-0',
    '0px': 'outline-offset-0',
    '1px': 'outline-offset-1',
    '2px': 'outline-offset-2',
    '4px': 'outline-offset-4',
    '8px': 'outline-offset-8'
  },
  overflow: {
    auto: 'overflow-auto',
    hidden: 'overflow-hidden',
    clip: 'overflow-clip',
    visible: 'overflow-visible',
    scroll: 'overflow-scroll'
  },
  'overflow-x': {
    auto: 'overflow-x-auto',
    hidden: 'overflow-x-hidden',
    clip: 'overflow-x-clip',
    visible: 'overflow-x-visible',
    scroll: 'overflow-x-scroll'
  },
  'overflow-y': {
    auto: 'overflow-y-auto',
    hidden: 'overflow-y-hidden',
    clip: 'overflow-y-clip',
    visible: 'overflow-y-visible',
    scroll: 'overflow-y-scroll'
  },
  cursor: {
    alias: 'cursor-alias',
    auto: 'cursor-auto',
    cell: 'cursor-cell',
    'context-menu': 'cursor-context-menu',
    copy: 'cursor-copy',
    crosshair: 'cursor-crosshair',
    default: 'cursor-default',
    grab: 'cursor-grab',
    grabbing: 'cursor-grabbing',
    help: 'cursor-help',
    move: 'cursor-move',
    'not-allowed': 'cursor-not-allowed',
    pointer: 'cursor-pointer',
    progress: 'cursor-progress',
    text: 'cursor-text',
    wait: 'cursor-wait',
    'zoom-in': 'cursor-zoom-in',
    'zoom-out': 'cursor-zoom-out'
  },
  'pointer-events': { none: 'pointer-events-none', auto: 'pointer-events-auto' },
  resize: { none: 'resize-none', both: 'resize', horizontal: 'resize-x', vertical: 'resize-y' },
  'user-select': {
    none: 'select-none',
    text: 'select-text',
    all: 'select-all',
    auto: 'select-auto'
  }
}
